version: '3.8'

services:
  php:
    build: .
    container_name: horoshop-php
    volumes:
      - ./:/var/www/horoshop
    ports:
      - "8000:8000"
    working_dir: /var/www/horoshop
    tty: true

  db:
    image: mysql:5.7
    container_name: horoshop-mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horoshop
      MYSQL_USER: root
      MYSQL_PASSWORD: F!93dh@L8v#ZxP$kU1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
